# Generated by Django 5.0.3 on 2024-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
